"""三库一体：标准库、业务数据库、知识库端口。"""

from __future__ import annotations

from typing import Any, Iterable, Protocol

from .domain import ClauseKnowledgeUnit, Entity, Rule


class StandardRepository(Protocol):
    def upsert(self, unit: ClauseKnowledgeUnit) -> None: ...
    def get_clause(self, clause_id: str, version: str | None = None) -> ClauseKnowledgeUnit | None: ...
    def search(self, filters: dict[str, Any], limit: int = 20) -> list[ClauseKnowledgeUnit]: ...
    def version_history(self, standard_id: str) -> list[str]: ...


class BusinessDataRepository(Protocol):
    def get_equipment_context(self, equipment_id: str) -> dict[str, Any]: ...
    def get_runtime_parameters(self, equipment_id: str, names: list[str]) -> dict[str, Any]: ...
    def get_verification_data(self, clause_id: str) -> list[dict[str, Any]]: ...


class KnowledgeGraphRepository(Protocol):
    def upsert_clause_graph(self, unit: ClauseKnowledgeUnit) -> None: ...
    def link_entities(self, names: Iterable[str], top_k: int) -> list[tuple[Entity, float]]: ...
    def rules_for_entities(self, entity_ids: Iterable[str]) -> list[Rule]: ...
    def traverse(self, entity_id: str, relations: list[str], max_depth: int) -> list[list[str]]: ...


class UnitOfWork(Protocol):
    standards: StandardRepository
    business_data: BusinessDataRepository
    graph: KnowledgeGraphRepository

    def commit(self) -> None: ...
    def rollback(self) -> None: ...

